config/routes.rb
LabSquares::Application.routes.draw do
  resources :nmapfiles do
    get "xmlviewer"
  end

  resources :jumpsizes
  

  authenticated :user do
    root :to => "jumpsquares#index"
  end
  
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "static_pages#home"
    end
  end
  
  devise_for :users, :path_names => { :sign_up => "register"}
  
  resources :jumpsizes
  resources :users
  resources :tags
  resources :apptype_requests
  
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/settings"
  get "static_pages/home"
  
  resources :jumpsquares do
    member {get "createrdpfile"}
  end
  
  resources :apptypes
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/jumpsquares', to: 'jumpsquares#index', via: 'get', as: :userroot
  match 'admin_dashboard/admindashboard', to: 'admin_dashboard#admindashboard', via: 'get', as: :admindashboard
  post 'users/:id/makeadmin' => 'users#makeadmin', as: :makeadmin
  post 'users/:id/removeadmin' => 'users#removeadmin', as: :removeadmin

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
 
end

app/controllers/apptypes_controller.rb
class ApptypesController < ApplicationController
  before_action :set_apptype, only: [:show, :edit, :update, :destroy]
  before_action :load_apptype, only: :create
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /apptypes
  # GET /apptypes.json
  def index
   @jumpsizes = Jumpsize.where(:jumpsizecreator => current_user.email)
   #grabs the search function and displays it all by name
   @apptypes = Apptype.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).order(sort_order('lower(name)'))
  end
    
  # GET /apptypes/1
  # GET /apptypes/1.json
  def show
  end

  # GET /apptypes/new
  def new
    @apptype = Apptype.new
  end

  # GET /apptypes/1/edit
  def edit
  end

  # POST /apptypes
  # POST /apptypes.json
  def create
    @apptype = Apptype.new(apptype_params)

    respond_to do |format|
      if @apptype.save
        format.html { redirect_to @apptype, notice: 'Apptype was successfully created.' }
        format.json { render action: 'show', status: :created, location: @apptype }
      else
        format.html { render action: 'new' }
        format.json { render json: @apptype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apptypes/1 
  # PATCH/PUT /apptypes/1.json
  def update
    respond_to do |format|
      if @apptype.update(apptype_params)
        format.html { redirect_to @apptype, notice: 'Apptype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @apptype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apptypes/1
  # DELETE /apptypes/1.json
  def destroy

      @apptype.destroy
        respond_to do |format|
          format.html { redirect_to apptypes_url }
          format.json { head :no_content }
        end 
    
    
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apptype
      @apptype = Apptype.find(params[:id])
    end
    
    def load_apptype
      @apptype = Apptype.new(apptype_params)
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def apptype_params
      params.require(:apptype).permit(:name, :image)
    end
   
end

app/helpers/apptypes_helper.rb
module ApptypesHelper
end

app/views/apptypes/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
            <div class="well">
            	<%= form_for @apptype, html: { multipart: true, :class => "form-horizontal" } do |f| %>
				  <% if @apptype.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@apptype.errors.count, "error") %> prohibited this Application Type from being saved:</h2>
				
				      <ul>
				      <% @apptype.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>
            	   
                <fieldset>
                  <legend><span class="glyphicon glyphicon-th" style="vertical-align:left"></span> AppType</legend>
                  <div class="form-group">
                  	<%= f.label "Application Type (Name):", :class => "col-lg-3 control-label" %>       
                    <div class="col-lg-7">
                      <%= f.text_field :name, :class => "form-control" %>                    	 
                    </div>
                  </div>
                                   
                  <div class="form-group">
                  	<%= f.label "Upload an Image or Logo:", :class => "col-lg-3 control-label" %>
                    <div class="col-lg-7">
                      <%= f.file_field :image %>
                    </div>
                  </div>                 
                                  
                  <br>
                  <center>
	                  <div class="form-group">	                    
	                      <%= f.submit class: 'btn btn-primary' %>
	                  </div>
	                  <%= link_to apptypes_path, class: "pull-left", :method => :get do %>
	        			<span class="glyphicon glyphicon-arrow-left" rel="tooltip" title="Back" style="vertical-align:left"></span> Back
	    			  <% end %>
	                     
	                  <%= link_to :userroot, class: "pull-right", :method => :get do %>
	        			Home <span class="glyphicon glyphicon-home" rel="tooltip" title="Home" style="vertical-align:left"></span>
	    			  <% end %>
                  </center>	 
                </fieldset>
              
            </div>
          </div>
        </div>
<% end %>

</html>

app/views/apptypes/edit.html.erb
<% provide(:title, 'Editing Application Type') %>


<%= render 'form' %>

app/views/apptypes/index.html.erb
<% provide(:title, 'AppType Settings') %>
<div class="row">
	 <div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
	 <div class="clearfix visible-xs"></div>
	 	<%= form_tag apptypes_path, :method => :get do %>
                      		<%= hidden_field_tag :direction, params[:direction] %>
  							<%= hidden_field_tag :sort, params[:sort] %> 							
    						<%= text_field_tag :search, params[:search], {:class => "form-control col-lg-8", :placeholder => "Search"} %>
					  <% end %>  
	 </div>	
	 	<div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-6 col-md-offset-6 col-sm-offset-6">
	 	<% if current_user.has_role? :admin %>
  			<%= link_to new_apptype_path, class: "btn btn-primary", :method => :get do %>
	        	<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> New Application Type
	    	<% end %>
  	 		</div>
     	<% else %>
			<%= link_to new_apptype_request_path, class: "btn btn-primary", :method => :get do %>
	        	<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> Request New Application Type
	    	<% end %>
	 		</div>
		<% end %>

</div>
		<% if current_user.has_role? :admin %>
		<% else %>
		<div class="row">
			<div class="col-xs-6 col-sm-4 col-md-2">
				<span class="label label-warning">AppTypes are Read-Only. Request a New Application Type if you do not see one listed.</span>
			</div>
		</div>
		<% end %>
<br>	

<div class="row">
	<div class="col-xs12 col-lg-11 col-md-11 col-sm-11 col-lg-offset-1 col-md-offset-1 col-sm-offset-1"
		<div id="apptypes">
  			<% @apptypes.each do |realapptype| %>
  		
    		<div class="apptype" style="float: left">
			    	
			     <% if @jumpsizes.first.size == "xsmall" %>
					<div class="xsmallname">
				 <% elsif @jumpsizes.first.size == "small" %>
					<div class="smallname">
				 <% elsif @jumpsizes.first.size == "medium" %>
					<div class="mediumname">
				 <% elsif @jumpsizes.first.size == "large" %>
					<div class="largename">
				 <% elsif @jumpsizes.first.size == "xlarge" %>
					<div class="xlargename">
				 <% end %>
    	

      			 <%= simple_format truncate(realapptype.name, :length => @jumpsizes.first.length1) %>
      				</div>
      			 
      			 <center><%= image_tag realapptype.image_url(@jumpsizes.first.size) %>
      
      			<% if current_user.has_role? :admin %>
		      	<br>
		      			<% if @jumpsizes.first.size == "xsmall" %>
							<div class="xsmallname">
							<% elsif @jumpsizes.first.size == "small" %>
							<div class="smallname">
							<% elsif @jumpsizes.first.size == "medium" %>
							<div class="mediumname">
							<% elsif @jumpsizes.first.size == "large" %>
							<div class="largename">
							<% elsif @jumpsizes.first.size == "xlarge" %>
							<div class="xlargename">
						<% end %>
			  <center>
		      		JumpSquares:  <span class="badge"><%= @appcount = Jumpsquare.where(['apptype = ?', realapptype.id]).count %></span>
		      				</div>
		      </center>
		      		    <% if @jumpsizes.first.size == "xsmall" %>
							<div class="xsmallactions">
						    <% elsif @jumpsizes.first.size == "small" %>
							<div class="smallactions">
						    <% elsif @jumpsizes.first.size == "medium" %>
							<div class="mediumactions">
						    <% elsif @jumpsizes.first.size == "large" %>
							<div class="largeactions">
						    <% elsif @jumpsizes.first.size == "xlarge" %>
							<div class="xlargeactions">
						<% end %>
			        
			        <%= link_to edit_apptype_path(realapptype), class: "pull-left", :method => :get do %>
				        <span class="glyphicon glyphicon-edit" rel="tooltip" title="Edit AppType" id='tooltip1' style="vertical-align:left"></span>
				    <% end %>
				    
				    <% if @appcount == 0 %>
				    	<%= link_to realapptype, class: "pull-right", :method => :delete, :data => {confirm: "Delete '#{realapptype.name}' AppType? "} do %>
				        	<span class="glyphicon glyphicon-trash" rel="tooltip" title="Delete AppType" id='tooltip1' style="vertical-align:left"></span>
				    	<% end %>
				   	<% end %>
		        			</div>
		      <% else %>
		      <% end %>
		     </div>
		    	
		  <% end %>
		</div>
	</div>
</div>
<center><%= will_paginate @apptypes, renderer: BootstrapPagination::Rails %></center>

app/views/apptypes/new.html.erb
<% provide(:title, 'New Application Type') %>


<%= render 'form' %>

app/views/apptypes/show.html.erb
<!DOCTYPE html>
<% provide(:title, @apptype.name) %>
<div class="row">
<div class="col-xs-6 col-sm-6 col-md-6 col-md-offset-4 col-sm-offset-4 col-xs-offset-4">
<div id="apptypes" >
    
     <div class="apptype" style="float: left">
      <div class="name"><%= @apptype.name %></div>
      <center><%= image_tag @apptype.image_url(:medium) %></center>
     <div class="actions">
     	<%= link_to "edit " + @apptype.name.to_s, edit_apptype_path(@apptype) %> |==|
        <%= link_to "apptypes", apptypes_path %> |==|
        <%= link_to "home", jumpsquares_path %>
        
      </div>
    </div>
	
	<div class="clear"></div>
</div>
</div>
</div>
</html>