config/routes.rb
LabSquares::Application.routes.draw do
  resources :nmapfiles do
    get "xmlviewer"
  end

  resources :jumpsizes
  

  authenticated :user do
    root :to => "jumpsquares#index"
  end
  
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "static_pages#home"
    end
  end
  
  devise_for :users, :path_names => { :sign_up => "register"}
  
  resources :jumpsizes
  resources :users
  resources :tags
  resources :apptype_requests
  
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/settings"
  get "static_pages/home"
  
  resources :jumpsquares do
    member {get "createrdpfile"}
  end
  
  resources :apptypes
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/jumpsquares', to: 'jumpsquares#index', via: 'get', as: :userroot
  match 'admin_dashboard/admindashboard', to: 'admin_dashboard#admindashboard', via: 'get', as: :admindashboard
  post 'users/:id/makeadmin' => 'users#makeadmin', as: :makeadmin
  post 'users/:id/removeadmin' => 'users#removeadmin', as: :removeadmin

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
 
end

app/models/tag.rb
class Tag < ActiveRecord::Base
   has_and_belongs_to_many :jumpsquares

  validates_presence_of :tagname

  def self.search(search)
    if search
      where('tagname ILIKE ? OR tagcreator ILIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :load_tag, only: :create
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /tags
  # GET /tags.json
  def index 
    @jumpsizes = Jumpsize.where(:jumpsizecreator => current_user.email)
    if current_user.has_role? :admin
      #uncomment to see ALL tags
      #@tags = Tag.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).order(sort_order('tagname'))
      @tags = Tag.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).where(:tagcreator => current_user.email).order(sort_order('tagname'))
    else
      @tags = Tag.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).where(:tagcreator => current_user.email).order(sort_order('tagname'))
    end
  end
  
  # GET /tags/1
  # GET /tags/1.json
  def show   
    @jumpsizes = Jumpsize.where(:jumpsizecreator => current_user.email)
    @jumpsquares = Jumpsquare.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).where(:jscreator => current_user.email).order(sort_order('name'))
    if current_user.has_role? :admin
      @tags = Tag.where(:tagcreator => current_user.email)
    else
      @tags = Tag.where(:tagcreator => current_user.email)
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = params[:tag][:tagname].split(/,\s*/)
    @tag.each do |t|
      newtag = Tag.new(:tagname => t, :tagcreator => current_user.email)
      newtag.save
    end
    #@tag = Tag.new(tag_params)
    redirect_to tags_path
    
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_path, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end
    
    def load_tag
      @tag = Tag.new(tag_params)
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tagname, :tagcreator)
    end
    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
            <div class="well">
            	<%= form_for @tag, html: {:class => "form-horizontal" } do |f| %>
				  <% if @tag.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>
				
				      <ul>
				      <% @tag.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>
            	
                <fieldset>
                  <legend><span class="glyphicon glyphicon-tag" style="vertical-align:left"></span> Tag</legend>
                  <div class="form-group">
                  	<%= f.label :tagname, "Tag Name:", :class => "col-lg-3 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.text_field :tagname, :class => "form-control" %>       
                       Use single entry or comma separated values. e.g. VMware, Microsoft, London, Network, Security          	 
                    </div>
                  </div>                                                
                  <br>
                  <center>
	                  <div class="form-group">
	                  	  <%= f.hidden_field :tagcreator, :value => current_user.email %>                    
	                      <%= f.submit class: 'btn btn-primary' %>
	                  </div>
	                  <%= link_to tags_path, class: "pull-left", :method => :get do %>
	        			<span class="glyphicon glyphicon-arrow-left" rel="tooltip" title="Back" style="vertical-align:left"></span> Back
	    			  <% end %>
	                     
	                  <%= link_to :userroot, class: "pull-right", :method => :get do %>
	        			Home <span class="glyphicon glyphicon-home" rel="tooltip" title="Home" style="vertical-align:left"></span>
	    			  <% end %>
                  </center>	 
                </fieldset>
              
            </div>
          </div>
        </div>
<% end %>

</html>

app/views/tags/edit.html.erb
<!DOCTYPE html>
<% provide(:title, "Editing " + @tag.tagname) %>



<%= render 'form' %>

</html>

app/views/tags/index.html.erb
<!DOCTYPE html>
<% provide(:title, "Tags") %>

<div class="row">
	 <div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
	 <div class="clearfix visible-xs"></div>
	 	<%= form_tag tags_path, :method => :get do %>
                      		<%= hidden_field_tag :direction, params[:direction] %>
  							<%= hidden_field_tag :sort, params[:sort] %> 							
    						<%= text_field_tag :search, params[:search], {:class => "form-control col-lg-8", :placeholder => "Search"} %>
					  <% end %>  
	 </div>	
	 <div class="col-xs-6 col-sm-4 col-md-2">	      
		<div class="btn-toolbar">
			<div class="btn-group">
				<button class="btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100">Sort By <b class="caret"></b></button>
					<ul class="dropdown-menu">
						<li><%= sort_link 'Name', :tagname %></li>
					</ul>
			</div>                   
	   </div>
  	</div>	
  	<div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-4 col-md-offset-4 col-sm-offset-4">
  		<%= link_to new_tag_path, class: "btn btn-primary", :method => :get do %>
	        <span class="glyphicon glyphicon-tag" style="vertical-align:left"></span> New Tag
	    <% end %>
   </div>
   
</div>
	
<br>

<div class="row">
		<% if current_user.has_role? :admin %>
          <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
        <% else %>
          <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
        <% end %>
            <div class="page-header">
              <h1 id="tables"><span class="glyphicon glyphicon-tags" style="vertical-align:left"></span> Tags</h1>
            </div>
            <div class="bs-example">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Tag</th>
                    <% if current_user.has_role? :admin %>
                    <th>Belongs to => Tag Creator</th>
                    <% else %>
                    <% end %>
                    <th>Actions</th>
                  </tr>
                </thead>
                
                	<tbody>
					    <% @tags.each do |tag| %>
					      <tr>
					        <td><%= tag.tagname %></td>
					        <% if current_user.has_role? :admin %>
					        <td><%= tag.tagcreator %></td>
					        <% else %>
                    		<% end %>
					        <td><%= link_to 'Show', tag, class: "btn btn-primary btn-xs" %> <%= link_to 'Edit', edit_tag_path(tag), class: "btn btn-warning btn-xs" %> <%= link_to 'Destroy', tag, method: :delete, data: { confirm: "Delete '#{tag.tagname}' Tag? " }, class: "btn btn-danger btn-xs" %></td>
					      </tr>
					    <% end %>
					  </tbody>
                  
                
              </table>
            </div>
          </div>
        </div>
      </div>
      <center><%= will_paginate @tags, renderer: BootstrapPagination::Rails %></center>
</html>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<!DOCTYPE html>
<% provide(:title, @tag.tagname) %>

<div class="row">
	 <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
	 <div class="clearfix visible-xs"></div>
	 	<%= form_tag jumpsquares_path, :method => :get do %>
                      		<%= hidden_field_tag :direction, params[:direction] %>
  							<%= hidden_field_tag :sort, params[:sort] %> 							
    						<%= text_field_tag :search, params[:search], {:class => "form-control col-lg-8", :placeholder => "Search"} %>
					  <% end %>  
	 </div>	
	 <div class="col-xs-4 col-sm-2 col-md-2">	      
		<div class="btn-toolbar">
			<div class="btn-group">
				<button class="btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100">Sort By <b class="caret"></b></button>
					<ul class="dropdown-menu">
						<li><%= sort_link 'Name', :name %></li>
						<li><%= sort_link 'Application Type', :apptype %></li>
						<li><%= sort_link 'IP or DNS', :ipordns %></li>
						<li><%= sort_link 'Jump URL', :url %></li>
					</ul>
			</div>                   
	    </div>
    </div>	
    <div class="col-xs-4 col-sm-2 col-md-2">
	  <center><strong><span class="glyphicon glyphicon-tag" style="vertical-align:left"></span> <%= @tag.tagname %></strong></center>
	  <p>
	  	<%= link_to edit_tag_path(@tag), class: "pull-left", :method => :get do %>
	        <span class="glyphicon glyphicon-edit" rel="tooltip" title="Edit Tag" style="vertical-align:left"></span>
	    <% end %>
	    <%= link_to :root, class: "pull-right", :method => :get do %>
	        <span class="glyphicon glyphicon-home" rel="tooltip" title="Home" style="vertical-align:left"></span>
	    <% end %>
	  </p>
	</div>
</div>
	
<br>
<div class="row">
	<div class="col-xs-4 col-sm-1 col-md-1 col-lg-1 col-lg-offset-1 col-md-offset-1 col-sm-offset-1"
		 <strong><span class="glyphicon glyphicon-tags" style="vertical-align:left"></span> Tags</strong>
	 	<% @tags.each do |tag| %>
	      <tr>
	        <% tagcount = tag.jumpsquares.count %>
	        	<% if tagcount > 0 %>
	        		<td>
	        			<%= button_to tag_path(tag.id), class: "btn btn-success btn-xs", :method => :get do %>
	        				<span class="glyphicon glyphicon-tag" style="vertical-align:left"></span> <%= tag.tagname + " [" + tag.jumpsquares.count.to_s + "]" %>
	    				<% end %>
	        		</td>
	        <% else %>
	        <% end %>								
	      </tr>
	    <% end %>
    
	</div>

	<div class="col-xs-8 col-sm-9 col-md-9 col-lg-9">
	<div id="apptypes" >
	  <% @jumpsquares.each do |jumpsquare| %>
	  		
	  		<% if jumpsquare.tags.include?(@tag) %>  
	  					
			    <div class="apptype" style="float: left">
			    	
			     <% if @jumpsizes.first.size == "xsmall" %>
					<div class="xsmallname">
				 <% elsif @jumpsizes.first.size == "small" %>
					<div class="smallname">
				 <% elsif @jumpsizes.first.size == "medium" %>
					<div class="mediumname">
				 <% elsif @jumpsizes.first.size == "large" %>
					<div class="largename">
				 <% elsif @jumpsizes.first.size == "xlarge" %>
					<div class="xlargename">
				 <% end %>
				 
					<% if jumpsquare.url == '' %>
					 		<%= truncate(jumpsquare.name, :length => @jumpsizes.first.length1) %>		
						</div>
				      	<center>
				      		<% apptype_id = Apptype.find(jumpsquare.apptype) %>
				      		<%= image_tag(apptype_id.image_url(@jumpsizes.first.size)) %>
				      	</center>
				 	<% else %>
							<%= link_to(truncate(jumpsquare.name, :length => @jumpsizes.first.length1), jumpsquare.url, :class => "popover-with-html", :title => jumpsquare.url, "data-content" => jumpsquare.description, :target => "_blank") %>		
						</div>
				      	<center>
				      		<% apptype_id = Apptype.find(jumpsquare.apptype) %>
				      		<%= link_to(image_tag(apptype_id.image_url(@jumpsizes.first.size)), jumpsquare.url, :class => "popover-with-html", :title => jumpsquare.url, "data-content" => jumpsquare.description, :target => "_blank") %>
				      	</center>     	
			     	<% end %>     	
			     
			     <% if @jumpsizes.first.size == "xsmall" %>
					<div class="xsmallactions">
				 <% elsif @jumpsizes.first.size == "small" %>
					<div class="smallactions">
				 <% elsif @jumpsizes.first.size == "medium" %>
					<div class="mediumactions">
				 <% elsif @jumpsizes.first.size == "large" %>
					<div class="largeactions">
				 <% elsif @jumpsizes.first.size == "xlarge" %>
					<div class="xlargeactions">
				 <% end %>	
			      <% if jumpsquare.remotetype == 'none' %>
				    	<%= truncate(jumpsquare.ipordns, :length => @jumpsizes.first.length2) %>
				    	<br>
				    <% elsif jumpsquare.remotetype == 'rdp' %>
				    	<%= link_to truncate(jumpsquare.ipordns, :length => @jumpsizes.first.length2), createrdpfile_jumpsquare_path(jumpsquare), :class => "popover-with-html", :title => "RDP", "data-content" => "RDP to " + jumpsquare.ipordns %>
				    	<br>
				    <% elsif jumpsquare.remotetype == 'ssh' %>
				    	<% sshaddress = "ssh://" + jumpsquare.ipordns.to_s %>
				    	<%= link_to truncate(jumpsquare.ipordns, :length => @jumpsizes.first.length2), sshaddress, :class => "popover-with-html", :title => "SSH", "data-content" => "SSH to " + jumpsquare.ipordns, :target => "_blank" %>
				    	<br>
				    <% elsif jumpsquare.remotetype == 'vnc' %>
				    	<% vncaddress = "http://" + jumpsquare.ipordns.to_s + ":5800" %>
				    	<%= link_to truncate(jumpsquare.ipordns, :length => @jumpsizes.first.length2), vncaddress, :class => "popover-with-html", :title => "VNC", "data-content" => "VNC to " + jumpsquare.ipordns, :target => "_blank" %>
				    	<br>
				    <% else %>
				    	<%= truncate(jumpsquare.ipordns, :length => @jumpsizes.first.length2) %>
				    	<br>
				    <% end %>
				        <%= link_to edit_jumpsquare_path(jumpsquare, :ipordns => jumpsquare.ipordns), class: "pull-left", :method => :get do %>
	        				<span class="glyphicon glyphicon-edit" rel="tooltip" title="Edit JumpSquare" id='tooltip1' style="vertical-align:left"></span>
	    				<% end %>
	    				
				        <%= link_to jumpsquare, class: "pull-right", :method => :delete, :data => {confirm: "Delete '#{jumpsquare.name}' JumpSquare? "} do %>
	        				<span class="glyphicon glyphicon-trash" rel="tooltip" title="Delete JumpSquare" id='tooltip2' style="vertical-align:left"></span>
	    				<% end %>
			      	</div>			      	
			    </div>
			 <% else %>
			 <% end %>
		    	
	 <% end %>
				  
	</div>
</div>
</div>
<center><%= will_paginate @jumpsquares, renderer: BootstrapPagination::Rails %></center>
<br>
</html>