config/routes.rb
LabSquares::Application.routes.draw do
  resources :nmapfiles do
    get "xmlviewer"
  end

  resources :jumpsizes
  

  authenticated :user do
    root :to => "jumpsquares#index"
  end
  
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "static_pages#home"
    end
  end
  
  devise_for :users, :path_names => { :sign_up => "register"}
  
  resources :jumpsizes
  resources :users
  resources :tags
  resources :apptype_requests
  
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/settings"
  get "static_pages/home"
  
  resources :jumpsquares do
    member {get "createrdpfile"}
  end
  
  resources :apptypes
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/jumpsquares', to: 'jumpsquares#index', via: 'get', as: :userroot
  match 'admin_dashboard/admindashboard', to: 'admin_dashboard#admindashboard', via: 'get', as: :admindashboard
  post 'users/:id/makeadmin' => 'users#makeadmin', as: :makeadmin
  post 'users/:id/removeadmin' => 'users#removeadmin', as: :removeadmin

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
 
end

app/models/apptype_request.rb
class ApptypeRequest < ActiveRecord::Base
  
  validates_presence_of :appname
  
  before_create :check_exists
  
  def check_exists
    requestedapp = Apptype.where(:name.downcase => self.appname.downcase)
    if requestedapp.exists?
      return false
    end
  end
  
  def self.search(search)
    if search
      where('apprequestor ILIKE ? OR appname ILIKE ? OR completed ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/controllers/apptype_requests_controller.rb
class ApptypeRequestsController < ApplicationController
  before_action :set_apptype_request, only: [:show, :edit, :update, :destroy]
  before_action :load_apptype_request, only: :create
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /apptype_requests
  # GET /apptype_requests.json
  def index
    @jumpsizes = Jumpsize.where(:jumpsizecreator => current_user.email) 
 
      if current_user.has_role? :admin
        @apptype_requests = ApptypeRequest.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).order(sort_order('completed'))
      else
        @apptype_requests = ApptypeRequest.search(params[:search]).paginate(:page => params[:page], :per_page => @jumpsizes.first.itemsperpage).where(:apprequestor => current_user.email).order(sort_order('completed'))
      end
  end

  # GET /apptype_requests/1
  # GET /apptype_requests/1.json
  def show
  end

  # GET /apptype_requests/new
  def new
    @apptype_request = ApptypeRequest.new
  end

  # GET /apptype_requests/1/edit
  def edit
  end

  # POST /apptype_requests
  # POST /apptype_requests.json
  def create
    
    @apptype_request = ApptypeRequest.new(apptype_request_params)
    @apptype_request.apprequestor = current_user.email
    @apptype_request.completed = false
    
    @admins = User.with_role :admin
    ApprequestMailer.user_request(@admins, @apptype_request).deliver
    
    respond_to do |format|
      if @apptype_request.save
        format.html { redirect_to @apptype_request, notice: 'Apptype request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @apptype_request }
      else
        flash[:notice] = "That AppType already exists. Go Search for it."
        format.html { render action: 'new', notice: 'That AppType already exists. Go Search for it.' }
        format.json { render json: @apptype_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apptype_requests/1
  # PATCH/PUT /apptype_requests/1.json
  def update
    respond_to do |format|
      
      if @apptype_request.update(apptype_request_params)
        format.html { redirect_to @apptype_request, notice: 'Apptype request was successfully updated.' }
        format.json { head :no_content }
          
         if @apptype_request.completed = true
           ApprequestMailer.admin_close(@apptype_request).deliver
         end
         
      else
        format.html { render action: 'edit' }
        format.json { render json: @apptype_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apptype_requests/1
  # DELETE /apptype_requests/1.json
  def destroy
    @apptype_request.destroy
    respond_to do |format|
      format.html { redirect_to apptype_requests_url }
      format.json { head :no_content }
    end
  end

  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apptype_request
      @apptype_request = ApptypeRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apptype_request_params
      params.require(:apptype_request).permit(:appname, :imageurl, :apprequestor, :completed)
    end
    
    def load_apptype_request
      @apptype_request = ApptypeRequest.new(apptype_request_params)
    end
    
end

app/helpers/apptype_requests_helper.rb
module ApptypeRequestsHelper
end

app/views/apptype_requests/_editform.html.erb
<!DOCTYPE html>
		<div class="row">
          <div class="col-lg-6 col-lg-offset-3">
            <div class="well">
            	<%= form_for @apptype_request, html: {:class => "form-horizontal" } do |f| %>
				  <% if @apptype_request.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@apptype_request.errors.count, "error") %> prohibited this apptype_request from being saved:</h2>
				
				      <ul>
				      <% @apptype_request.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>	
                <fieldset>               	
                  <legend>AppType</legend>
                  <div class="form-group">
                  	<%= f.label :apprequestor, "Requester:", :class => "col-lg-3 control-label" %>        
                    <div class="col-lg-7">
                      <%= f.text_field :apprequestor, :value=> current_user.email, :class => "form-control", :disabled => ""  %>	 
                    </div>
                  </div>
                  <div class="form-group">                 	
                  	<%= f.label :appname, "AppType Name", :class => "col-lg-3 control-label" %>
                    <div class="col-lg-7">
                      <% if @apptype_request.completed == false %>
                      <%= f.text_field :appname, :class => "form-control" %> 
                      <% else %>     
                      <%= f.text_field :appname, :class => "form-control", :disabled => "" %>    
                      <% end %>          	 
                    </div>
                  </div>                                                
                  <br>
                  <div class="form-group">
                  	<%= f.label :imageurl, "URL to Image (optional)", :class => "col-lg-3 control-label" %>     
                    <div class="col-lg-7">
                      <% if @apptype_request.completed == false %>	
                      <%= f.text_field :imageurl, :class => "form-control" %>    
                      <% else %>                  	 
                      <%= f.text_field :imageurl, :class => "form-control", :disabled => "" %>   
                      <% end %>      
                    </div>
                  </div>                                                
                  <br>
                  
                  <% if current_user.has_role? :admin %>             
                  <div class="form-group">
                  	<%= f.label :completed, "Complete", :class => "col-lg-3 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.check_box :completed, :class => "form-control" %>                   	 
                    </div>
                  </div>                                                
                  <br>
                  <% else %>
                  <% end %>
                  
                  <center>
	                  <div class="form-group">                
	                      <%= f.submit class: 'btn btn-primary' %>
	                  </div>
	                  <%= link_to 'Back', :back %> |
					  <%= link_to 'Home', :userroot %> | 
					  <%= link_to 'AppType Requests', apptype_requests_path %>
                  </center>	 
                </fieldset>
              
            </div>
          </div>
        </div>
<% end %>

</html>

app/views/apptype_requests/_form.html.erb
<!DOCTYPE html>
<center><div class="alert"><%= notice %><%= alert %></div></center>
		<div class="row">
          <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
            <div class="well">
            	<%= form_for @apptype_request, html: {:class => "form-horizontal" } do |f| %>
				  <% if @apptype_request.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@apptype_request.errors.count, "error") %> prohibited this apptype_request from being saved:</h2>
				
				      <ul>
				      <% @apptype_request.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>	
                <fieldset>               	
                  <legend><span class="glyphicon glyphicon-asterisk" style="vertical-align:left"></span> AppType</legend>
                  <div class="form-group">
                  	<%= f.label :apprequestor, "Requester:", :class => "col-lg-3 control-label" %>        
                    <div class="col-lg-7">
                      <%= f.text_field :apprequestor, :value=> current_user.email, :class => "form-control", :disabled => ""  %>	 
                    </div>
                  </div>
                  <div class="form-group">                 	
                  	<%= f.label :appname, "AppType Name", :class => "col-lg-3 control-label" %>
                    <div class="col-lg-7">
                      <%= f.text_field :appname, :class => "form-control" %>          	 
                    </div>
                  </div>                                                
                  <br>
                  <div class="form-group">
                  	<%= f.label :imageurl, "URL to Image (optional) (please use transparent square images, such as 200x200 & .png)", :class => "col-lg-3 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.text_field :imageurl, :class => "form-control" %>                	     
                    </div>
                  </div>                                                
                  <br>
                  
                  <% if current_user.has_role? :admin %>             
                  <div class="form-group">
                  	<%= f.label :completed, "Complete", :class => "col-lg-3 control-label" %>     
                    <div class="col-lg-7">
                      <%= f.check_box :completed, :class => "form-control" %>                   	 
                    </div>
                  </div>                                                
                  <br>
                  <% else %>
                  <% end %>
                  
                  <center>
	                  <div class="form-group">                
	                      <%= f.submit "Submit AppType Request", class: 'btn btn-primary' %>
	                  </div>
	                  <%= link_to :back, class: "pull-left", :method => :get do %>
	        			<span class="glyphicon glyphicon-arrow-left" rel="tooltip" title="Back" style="vertical-align:left"></span> Back
	    			  <% end %>
	                     
	                  <%= link_to :userroot, class: "pull-right", :method => :get do %>
	        			Home <span class="glyphicon glyphicon-home" rel="tooltip" title="Home" style="vertical-align:left"></span>
	    			  <% end %>
					  
                  </center>	 
                </fieldset>
              
            </div>
          </div>
        </div>
<% end %>

</html>

app/views/apptype_requests/edit.html.erb
<%= render 'editform' %>

app/views/apptype_requests/index.html.erb
<div class="row">
	 <div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
	 <div class="clearfix visible-xs"></div>
	 	<%= form_tag apptype_requests_path, :method => :get do %>
                      		<%= hidden_field_tag :direction, params[:direction] %>
  							<%= hidden_field_tag :sort, params[:sort] %> 							
    						<%= text_field_tag :search, params[:search], {:class => "form-control col-lg-8", :placeholder => "Search"} %>
					  <% end %>  
	 </div>	
	 <div class="col-xs-6 col-sm-4 col-md-2">	      
		<div class="btn-toolbar">
			<div class="btn-group">
				<button class="btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="100">Sort By <b class="caret"></b></button>
					<ul class="dropdown-menu">
						<li><%= sort_link 'Requester', :apprequestor %></li>
						<li><%= sort_link 'Application Name', :appname %></li>
						<li><%= sort_link 'Completed', :completed %></li>
					</ul>
			</div>                   
	   </div>
  	</div>	
  	<div class="col-xs-6 col-sm-4 col-md-2 col-lg-offset-4 col-md-offset-4 col-sm-offset-4">
  		<% if current_user.has_role? :admin %>
  			<%= link_to new_apptype_request_path, class: "btn btn-primary", :method => :get do %>
	        	<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> Request Application Type
	    	<% end %> 
  			<%= link_to new_apptype_path, class: "btn btn-primary", :method => :get do %>
	        	<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> New Application Type
	    	<% end %>
     	<% else %>
			<%= link_to new_apptype_request_path, class: "btn btn-primary", :method => :get do %>
	        	<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> Request Application Type
	    	<% end %>
		<% end %>
	</div>
</div>

<div class="row">
          <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
          	
            <div class="page-header">
              <h1 id="tables"><span class="glyphicon glyphicon-asterisk" style="vertical-align:left"></span> AppType Requests</h1>
            </div>
            <div class="bs-example">
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
					<th>Requester</th>
					<th>Application Name</th>
				    <th>Image URL</th>		    
				    <th>Completed?</th>
                    <th></th>
                    <% if current_user.has_role? :admin %>
                    <th></th>
                    <th></th>
                    <% else %>
                    <% end %>
                  </tr>
                </thead>
                
                	<tbody>
					    <% @apptype_requests.each do |apptype_request| %>
					      <tr>
					        <td><%= apptype_request.apprequestor %></td>
					        <td><%= apptype_request.appname %></td>
					        <td><%= apptype_request.imageurl %></td>					        
					        <td><%= apptype_request.completed %></td>
					        <td><%= link_to 'Edit', edit_apptype_request_path(apptype_request), class: "btn btn-warning btn-xs" %></td>
					        <% if current_user.has_role? :admin %>
					        <td><%= link_to 'Show', apptype_request, class: "btn btn-primary btn-xs" %></td>
					        <td><%= link_to 'Destroy', apptype_request, method: :delete, class: "btn btn-danger btn-xs" %></td>
					        <% else %>
                    		<% end %>
					      </tr>
					    <% end %>
					  </tbody>
                  
                
              </table>
            </div>
          </div>
        </div>
      </div>
      <center><%= will_paginate @apptype_requests, renderer: BootstrapPagination::Rails %></center>
</html>

app/views/apptype_requests/new.html.erb
<% provide(:title, 'New Request') %>
<%= render 'form' %>

app/views/apptype_requests/show.html.erb
<div class="row">
          <div class="col-lg-6 col-lg-offset-3">
            <div class="well">
				<p>
				  <strong>AppType Requester:</strong>
				  <%= @apptype_request.apprequestor %>
				</p>
				<p>
				  <strong>Application Name:</strong>
				  <%= @apptype_request.appname %>
				</p>
				<p>
				  <strong>Image URL:</strong>
				  <%= @apptype_request.imageurl %>
				</p>
				<% if current_user.has_role? :admin %>
				<p>
				  <strong>Completed?:</strong>
				  <%= @apptype_request.completed %>
				</p>
				<% else %>
                <% end %>
			<center>
				<%= link_to 'Edit', edit_apptype_request_path(@apptype_request) %> |
				<%= link_to 'Back', :back %> |
				<%= link_to 'AppType Requests', apptype_requests_path %>
			</center>
			</div>
		</div>
	</div>	