config/routes.rb
LabSquares::Application.routes.draw do
  resources :nmapfiles do
    get "xmlviewer"
  end

  resources :jumpsizes
  

  authenticated :user do
    root :to => "jumpsquares#index"
  end
  
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "static_pages#home"
    end
  end
  
  devise_for :users, :path_names => { :sign_up => "register"}
  
  resources :jumpsizes
  resources :users
  resources :tags
  resources :apptype_requests
  
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/settings"
  get "static_pages/home"
  
  resources :jumpsquares do
    member {get "createrdpfile"}
  end
  
  resources :apptypes
  match '/help', to: 'static_pages#help', via: 'get', as: :help
  match '/contact', to: 'static_pages#contact', via: 'get', as: :contact
  match '/about', to: 'static_pages#about', via: 'get', as: :about
  match '/jumpsquares', to: 'jumpsquares#index', via: 'get', as: :userroot
  match 'admin_dashboard/admindashboard', to: 'admin_dashboard#admindashboard', via: 'get', as: :admindashboard
  post 'users/:id/makeadmin' => 'users#makeadmin', as: :makeadmin
  post 'users/:id/removeadmin' => 'users#removeadmin', as: :removeadmin

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
 
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">	 
          <div class="col-lg-12">
			  <small>
			    <a href="http://kendrickcoleman.com/index.php/Ruby-on-Rails-Projects/jumpsquares-a-new-kind-of-bookmark.html">JumpSquares</a>
			    by Kendrick Coleman
			  </small>
			  <nav>
			    <ul>
			       <ul class="nav pull-right">
			       		<li><%= link_to "About",   :about %></li>
			       	</ul>
			      <ul class="nav pull-right">
			      		<li><%= link_to "Contact", :contact %></li>
			      	</ul>
			    </ul>
			  </nav>
		</div>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');		
		  ga('create', 'UA-45664110-1', 'jumpsquares.net');
		  ga('require', 'displayfeatures');
		  ga('send', 'pageview');		
		</script>		
</footer>

app/views/layouts/_header.html.erb
  <div class="bs-docs-section clearfix">
  	 <div class="row">
          <div class="col-lg-12">
            <div class="page-header">
            </div>
 		  </div>
 	 </div>
  </div>
 
 <div class="navbar navbar-default navbar-fixed-top">
 	<div class="navbar-inner">
      <div class="container">
        <div class="navbar-header">
	         <% if user_signed_in? %>	         	
	         	<%= link_to image_tag("medium_jumpsquares_logo.png", :height => '25', :width => '25'), :userroot, class: "navbar-brand" %>
	         	<%= link_to "JumpSquares", :userroot, class: "navbar-brand" %>
	       	 <% else %>
	        	<%= link_to image_tag("medium_jumpsquares_logo.png", :height => '25', :width => '25'), :root, class: "navbar-brand" %>
	         	<%= link_to "JumpSquares", :root, class: "navbar-brand" %>
	         <% end %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        
        
      <% if user_signed_in? %>
        <div class="navbar-collapse collapse pull-right nav-collapse" id="navbar-main">              
          <ul class="nav navbar-nav">
			<li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="settings"><span class="glyphicon glyphicon-plus-sign" style="vertical-align:left"></span> New<span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="settings">
              	<li><%= link_to new_jumpsquare_path do %>
              		<span class="glyphicon glyphicon-stop" style="vertical-align:left"></span> JumpSquare
              		<% end %>
              	</li>
              	<li><%= link_to new_tag_path do %>
              		<span class="glyphicon glyphicon-tag" style="vertical-align:left"></span> Tag
              		<% end %>
              	</li>
              	<li><%= link_to new_apptype_request_path do %>
              		<span class="glyphicon glyphicon-asterisk" style="vertical-align:left"></span> AppType Request
              		<% end %>
              	</li>
              	<li><%= link_to new_nmapfile_path do %>
              		<span class="glyphicon glyphicon-eye-open" style="vertical-align:left"></span> Nmap Scan XML
              		<% end %>
              	</li>
              	<% if current_user.has_role? :admin %>
		        <li><%= link_to new_apptype_path do %>
              		<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> New Apptype
              		<% end %>
              	</li>
		        <% end %>
              </ul>
            </li>
            
            <li>
               <li><%= link_to :help do %>
              		<span class="glyphicon glyphicon-info-sign" style="vertical-align:left"></span> Help
              		<% end %>
              	</li>
            </li>
            
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="settings"><span class="glyphicon glyphicon-cog" style="vertical-align:left"></span> Settings <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="settings">
              	<li><%= link_to apptypes_path do %>
              		<span class="glyphicon glyphicon-th" style="vertical-align:left"></span> AppTypes
              		<% end %>
              	</li>
              	<li><%= link_to tags_path do %>
              		<span class="glyphicon glyphicon-tags" style="vertical-align:left"></span> Tags
              		<% end %>
              	</li>
              	<li><%= link_to jumpsizes_path do %>
              		<span class="glyphicon glyphicon-th-list" style="vertical-align:left"></span> Size & Sort
              		<% end %>
              	</li>
              	<li><%= link_to nmapfiles_path do %>
              		<span class="glyphicon glyphicon-eye-open" style="vertical-align:left"></span> Nmap Scans
              		<% end %>
              	</li>
              	<% if current_user.has_role? :admin %>
		        <li><%= link_to apptype_requests_path do %>
              		<span class="glyphicon glyphicon-asterisk" style="vertical-align:left"></span> All AppType Requests
              		<span class="badge"><%= ApptypeRequest.where(:completed => false ).count %></span>
              		<% end %>
              	</li>
		        <% else %>
		        <li><%= link_to apptype_requests_path do %>
              		<span class="glyphicon glyphicon-asterisk" style="vertical-align:left"></span> AppType Requests
              		<span class="badge"><%= ApptypeRequest.where(:apprequestor => current_user.email, :completed => false).count %></span>
              		<% end %>
              	</li>
		        <% end %>	
		        <li><%= link_to edit_user_registration_path do %>
              		<span class="glyphicon glyphicon-user" style="vertical-align:left"></span> Manage Account
              		<% end %>
              	</li>
		        <% if current_user.has_role? :admin %>
		        <li><%= link_to users_path do %>
              		<span class="glyphicon glyphicon-wrench" style="vertical-align:left"></span> Manage Users
              		<% end %>
              	</li>
		        <li><%= link_to :admindashboard do %>
              		<span class="glyphicon glyphicon-stats" style="vertical-align:left"></span> Admin Dashboard
              		<% end %>
              	</li>
		        <% else %>
		        <% end %>          
				<li><%= link_to destroy_user_session_path, method: :delete do %>
              		<span class="glyphicon glyphicon-off" style="vertical-align:left"></span> Logout
              		<% end %>
              	</li>
              </ul>
            </li>
		 </ul>	
       </div>
        
      <% else %>
      
	   <div class="navbar-collapse collapse pull-right" id="navbar-main">              
		  <ul class="nav navbar-nav"> 		 
	          <li><%= link_to  new_user_registration_path, :method => :get do %>
	                	<span class="glyphicon glyphicon-pencil" style="vertical-align:left"></span> Register
	                <% end %></li>
		      <li><%= link_to  new_user_session_path, :method => :get do %>
	                	<span class="glyphicon glyphicon-user" style="vertical-align:left"></span> Login
	                <% end %></li>		            	
		  </ul> 
	   </div>
      <% end %>
     
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Lato:400,700,900,400italic', media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
		<%= render 'layouts/header' %>
    <div class="container-fluid">
      		 	 <!--[if IE]>
<center><strong>Are you wondering why this site looks like garbage? <br>
	It's because you are using Internet Explorer. <br>
	Use a browser with standards, preferebly Firefox.</strong></center>
	<![endif]-->
      	<center>  	 
	      	<div class="alert alert-warning alert-dismissable hide" style="width:400px">
	            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	            <%= notice %><%= alert %>
	        </div>
       </center>
       
      	<%= yield %>

		<script>			
			$(function (){
				$('.dropdown-toggle').dropdown();
				$('.popover-with-html').popover({ html: true, trigger: "hover", delay: 250});
				$(".alert").delay(400).addClass("in");
				$("[rel=tooltip]").tooltip({ placement: 'bottom'});
			});
		</script>
    </div>
   		<%= render 'layouts/footer' %>
  </body>
</html>